// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by pvtro
// Found 3 slang packages

// ignore_for_file: no_leading_underscores_for_library_prefixes, depend_on_referenced_packages, library_prefixes

import 'package:flutter/widgets.dart';

import 'package:integration_check_1/i18n/translations.g.dart' as _$0;
import 'package:feature_shell/i18n/translations.g.dart' as _$1;
import 'package:shared_checkout_i18n/i18n/translations.g.dart' as _$2;

Widget pvtroWrapper({required Widget child}) {
  return _$0.TranslationProvider(
    child: _$1.TranslationProvider(
      child: _$2.TranslationProvider(
        child: child,
      ),
    ),
  );
}

Future<void> pvtroSyncPackageLocales(String rawLocale) async {
  await Future.wait([
    _$0.LocaleSettings.setLocaleRaw(rawLocale),
    _$1.LocaleSettings.setLocaleRaw(rawLocale),
    _$2.LocaleSettings.setLocaleRaw(rawLocale),
  ]);
}
