import 'package_scanner.dart';

/// Generate import statements with indexed aliases (_$0, _$1, etc.)
String generateImports(List<SlangPackageInfo> packages) {
  final buffer = StringBuffer();

  for (var i = 0; i < packages.length; i++) {
    buffer.writeln("import '${packages[i].importPath}' as _\$$i;");
  }

  return buffer.toString();
}

/// Generate nested TranslationProvider wrapper function
/// Order: main_app (outermost) → dependencies → child (innermost)
String generateWrapper(List<SlangPackageInfo> packages) {
  if (packages.isEmpty) {
    return '''
Widget pvtroWrapper({required Widget child}) {
  return child;
}
''';
  }

  final buffer = StringBuffer();
  buffer.writeln('Widget pvtroWrapper({required Widget child}) {');
  
  // Build nested TranslationProviders
  // First package (main) is outermost, last is innermost around child
  for (var i = 0; i < packages.length; i++) {
    final indent = '  ' * (i + 1);
    if (i == 0) {
      buffer.writeln('  return _\$$i.TranslationProvider(');
    } else {
      buffer.writeln('${indent}child: _\$$i.TranslationProvider(');
    }
  }
  
  // The innermost child
  final deepestIndent = '  ' * (packages.length + 1);
  buffer.writeln('${deepestIndent}child: child,');
  
  // Close all providers (reverse order)
  for (var i = packages.length - 1; i >= 0; i--) {
    final indent = '  ' * (i + 1);
    buffer.write('$indent)');
    if (i > 0) {
      buffer.writeln(',');
    } else {
      buffer.writeln(';');
    }
  }
  
  buffer.writeln('}');

  return buffer.toString();
}

/// Generate the complete output file content
String generateOutputFile(List<SlangPackageInfo> packages) {
  final buffer = StringBuffer();

  // Header
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by pvtro');
  buffer.writeln('// Found ${packages.length} slang packages');
  buffer.writeln();
  buffer.writeln('// ignore_for_file: depend_on_referenced_packages, library_prefixes');
  buffer.writeln();

  // Flutter import
  buffer.writeln("import 'package:flutter/widgets.dart';");
  buffer.writeln();

  // Package imports
  buffer.write(generateImports(packages));
  buffer.writeln();

  // Wrapper function
  buffer.write(generateWrapper(packages));

  return buffer.toString();
}
